name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
    
    - name: Run yarn install
      uses: bahmutov/npm-install@v1

    - name: Run tools/test
      run: TERM=dumb tools/test --full

    - run: tools/verify-webview-js
